# Generated by Django 2.0.1 on 2018-01-04 15:30

import datetime
from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Max 250 characters', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the cagegory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 250 characters', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique for publish date.', unique_for_date='publish_date')),
                ('excerpt', models.TextField(blank=True, help_text='A short summary. Optional')),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Lets you feature a blog post. Typically the most recent featured blog post will show up different')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Controls if a blog post is published on the site')),
                ('thumbnail', filebrowser.fields.FileBrowseField(blank=True, help_text='An optional thumbnail for the listing page', max_length=200)),
                ('categories', models.ManyToManyField(blank=True, help_text='The categories for the Blog Post', related_name='posts', to='blog.Category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ('-publish_date', 'slug'),
            },
        ),
    ]
