# Generated by Django 2.0.1 on 2018-01-04 15:30

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_heading', models.CharField(blank=True, help_text='An optional sub heading / short teaser', max_length=250)),
                ('image', filebrowser.fields.FileBrowseField(help_text='Banner image. This will be cropped to fit the size needed for the banner group', max_length=200)),
                ('url', models.CharField(blank=True, help_text='Optional URL that the banner can link to', max_length=250)),
                ('url_name', models.CharField(blank=True, help_text='Optional display text to be used for the link. May not be used in all banner groups.', max_length=50)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=1, help_text='Controls the order that banners are displayed')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique Identifier for a group of banners', unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description to know what this group is used for')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups that this banner belongs to. This decides where a banner shows up  on the site and how it is displayed.', to='promotions.BannerGroup'),
        ),
    ]
